# Generated by Django 3.2.9 on 2021-11-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_auto_20211109_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
