# Generated by Django 3.2.9 on 2021-11-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_contributors_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='assignee_user_id',
            new_name='author_user',
        ),
    ]
